name: Run Java Integration Tests and Samples

on:
  workflow_dispatch:
  push:
    branches: [ "experimental-java", "java-dev" ]
    paths:
      - 'java/**'
      - 'samples/java/**'
  pull_request:
    branches: [ "experimental-java", "java-dev" ]
    paths:
      - 'java/**'
      - 'samples/java/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-versions: [jdk8, jdk11, jdk17]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Need to use different JDK for JDK 8
      - name: Set JDK
        id: set-jdk
        shell: bash
        run: |
          if [[ ${{ matrix.java-versions }} == "jdk8" ]]; then
            echo "JDK_VERSION=11" >> $GITHUB_OUTPUT
          else
            version=$(echo ${{ matrix.java-versions }} | sed 's/jdk//')
            echo "JDK_VERSION=$version" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.set-jdk.outputs.JDK_VERSION }}
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B -Pbug-check -DskipTests -X -Pcompile-${{ matrix.java-versions }} clean install --file pom.xml
        working-directory: java

      - name: Run Tests
        run: ../mvnw -B -Pbug-check clean install --file pom.xml
        working-directory: java/api-test

      - name: Build samples
        run: cd java/samples && ../mvnw -B clean install --file pom.xml
